const cfg = window.ASAI_CONFIG || {};
const toolNames = {obd:'OBD / testeri',multimeter:'yleismittari',scope:'oskilloskooppi',clamp:'virtapihti',pressure:'paine-/alipainemittari',smoke:'savukone'};
const form=document.getElementById('diagnosis-form'),panel=document.getElementById('result-panel'),content=document.getElementById('result-content');
const continueBox=document.getElementById('continue-box'),paywallBox=document.getElementById('paywall-box'),accessStatus=document.getElementById('access-status'),accessCode=document.getElementById('access-code'),sourceStrip=document.getElementById('source-strip');
let latestText='', caseData=null, history=[], activeAccess=null;

const menuButton=document.querySelector('.menu-button'),mainNav=document.querySelector('.main-nav');
menuButton?.addEventListener('click',()=>{const open=mainNav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));});
mainNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mainNav.classList.remove('open');menuButton?.setAttribute('aria-expanded','false');}));
document.getElementById('year').textContent=new Date().getFullYear();
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));

function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function tools(fd){return fd.getAll('tools');}
function workerReady(){return cfg.workerUrl && !cfg.workerUrl.includes('VAIHDA-TAMA');}
function normalizeCode(v){return String(v||'').trim().toUpperCase();}
function getClientId(){let id=localStorage.getItem('asai_client_id');if(!id){id=(crypto.randomUUID?crypto.randomUUID():('c-'+Date.now()+'-'+Math.random().toString(36).slice(2)));localStorage.setItem('asai_client_id',id);}return id;}
function freeUsed(){return localStorage.getItem('asai_free_used')==='1';}
function setAccessStatus(text,state=''){accessStatus.textContent=text;accessStatus.className='access-status'+(state?' '+state:'');}

// EezyPay links are configured in config.js.
document.querySelectorAll('.pay-link').forEach(a=>{const plan=a.dataset.plan;const url=cfg.paymentLinks?.[plan];if(url && !url.includes('VAIHDA-EEZYPAY')){a.href=url;a.target='_blank';a.rel='noopener';}else{a.addEventListener('click',e=>{e.preventDefault();alert('EezyPay-maksulinkki lisätään tähän ennen julkaisua. Muokkaa config.js-tiedostoa.');});}});

async function api(path,body){if(!workerReady()) throw new Error('AI-palvelimen osoitetta ei ole vielä määritetty config.js-tiedostoon.');const r=await fetch(cfg.workerUrl.replace(/\/$/,'')+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let data={};try{data=await r.json();}catch{}if(!r.ok) throw new Error(data.error||'Palvelinvirhe');return data;}

async function activate(){const code=normalizeCode(accessCode.value);if(!code){activeAccess=null;setAccessStatus(freeUsed()?'Ilmainen mittausohje on jo käytetty tällä selaimella.':'Ilmainen AI-vastaus käytettävissä.');return;}setAccessStatus('Tarkistetaan koodia…');try{const x=await api('/activate',{code});activeAccess={code,...x};localStorage.setItem('asai_access_code',code);setAccessStatus(`Aktivoitu: ${x.label}. ${x.remainingText||''}`,'ok');}catch(e){activeAccess=null;localStorage.removeItem('asai_access_code');setAccessStatus(e.message,'bad');}}
document.getElementById('activate-code').addEventListener('click',activate);
accessCode.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();activate();}});
const saved=localStorage.getItem('asai_access_code');if(saved){accessCode.value=saved;activate();}else if(freeUsed()){setAccessStatus('Ilmainen mittausohje on jo käytetty tällä selaimella.');}

function localFreePlan(data){const dtc=(data.dtc||'').toUpperCase(),s=(data.symptom||'').toLowerCase(),has=t=>data.tools.includes(t);
 if(/P0171|P0174/.test(dtc)||/laiha|seos/.test(s)){return has('obd')?{test:data.mode==='consumer'?'Vertaa polttoaineen seoskorjauksia tyhjäkäynnillä ja noin 2500 rpm':'Vertaa STFT- ja LTFT-arvoja tyhjäkäynnillä ja noin 2500 rpm',tool:'OBD / testeri',how:data.mode==='consumer'?'Lämmitä moottori käyttölämpöiseksi. Avaa OBD-sovelluksesta Polttoaineen lyhytaikainen korjaus (STFT) ja Polttoaineen pitkäaikainen korjaus (LTFT). Kirjaa molemmat prosenttiarvot ensin tyhjäkäynnillä ja sitten tasaisella noin 2500 rpm kierrosluvulla.':'Lämmitä moottori käyttölämpöiseksi. Kirjaa STFT ja LTFT tyhjäkäynnillä sekä tasaisella noin 2500 rpm kierrosluvulla.',expected:data.mode==='consumer'?'Arvot näytetään prosentteina. Selvästi plusmerkkinen arvo tarkoittaa, että moottorinohjaus joutuu lisäämään polttoainetta normaalia enemmän. Älä päättele osavikaa yhden arvon perusteella.':'Seoskorjausten pitäisi pysyä lähellä normaalia. Selvästi positiivinen korjaus kertoo ECU:n lisäävän polttoainetta.',ok:data.mode==='consumer'?'Kirjaa ylös STFT- ja LTFT-prosentit molemmilla kierrosluvuilla. Maksullinen AI-jatko käyttää niitä seuraavan mittauksen valintaan.':'Syötä molemmat arvot AI:lle. Kierrosluvun mukana selvästi pienenevä korjaus voi ohjata imuvuodon tutkimiseen.',bad:data.mode==='consumer'?'Jos korjausarvot ovat selvästi poikkeavat, älä vaihda osia vielä. Seuraava vaihe on rajata syytä mittauksilla.':'Jos arvot ovat suuret kaikilla kierroksilla, seuraava haara voi olla ilmamäärän, polttoainepaineen tai anturidatan tarkistus.',reason:data.mode==='consumer'?'Vertailu kertoo, muuttuuko ongelma moottorin kierrosluvun mukana. Se auttaa valitsemaan seuraavan järkevän testin ilman osien arvaamista.':'Kahden käyttötilanteen vertailu auttaa erottamaan ilmavuodon muista laihan seoksen syistä.'}:{test:'Lue vikakoodit ja freeze frame -tiedot',tool:'OBD-lukija',how:'Lue koodit ennen nollausta ja tallenna freeze frame, jos laite näyttää sen.',expected:'Tavoite on saada moottorin kuormitus-, lämpötila- ja seosdata vian hetkeltä.',ok:'Syötä koodit ja freeze frame -tiedot AI:lle.',bad:'Jos OBD-dataa ei saada, tarkista 12 V järjestelmä ja diagnostiikkapistokkeen syöttö ammattilaisen ohjeella.',reason:'Vikakoodi yksin ei kerro juurisyytä.'};}
 if(/P0101/.test(dtc)||/maf|ilmamäär/.test(s)) return {test:'Tarkista MAF-livedatan loogisuus',tool:has('obd')?'OBD / testeri':'Perustarkastus',how:has('obd')?'Seuraa MAF-arvoa tyhjäkäynnillä ja nosta kierroksia tasaisesti. Kirjaa arvot.':'Tarkista imuletkut, liittimet ja näkyvät vuodot ennen osien vaihtoa.',expected:'Ilmamäärän pitäisi muuttua tasaisesti moottorin ilmantarpeen mukana.',ok:'Syötä arvot AI:lle jatkoa varten.',bad:'Älä tuomitse MAF-anturia ennen syötön, maan, signaalin ja ilmavuotojen tarkistusta.',reason:'P0101 on uskottavuusvika, ei automaattisesti viallinen MAF.'};
 if(/U0[0-9A-F]{2}|U1[0-9A-F]{2}/.test(dtc)||/can|väyl|kommunik/.test(s)) return {test:'Kirjaa kaikki kommunikaatiovikakoodit ja moduulit, joihin testerillä ei päästä',tool:'OBD / testeri',how:'Tee koko auton vikakoodiluku. Merkitse mitkä moduulit vastaavat ja mitkä eivät.',expected:'Vikakoodien jakauma auttaa paikantamaan, onko kyse yhdestä moduulista vai yhteisestä väylästä/syötöstä.',ok:'Syötä lista AI:lle. Mekaanikko-tilassa voidaan jatkaa vastus- tai skooppimittaukseen.',bad:'Jos yhteys koko autoon puuttuu, tarkista ensin diagnostiikkapistokkeen ja 12 V järjestelmän perusedellytykset.',reason:'Verkon topologiaa voi rajata jo sillä, ketkä moduulit ovat saavutettavissa.'};
 return {test:'Lue vikakoodit ja tallenna vian esiintymisolosuhteet',tool:has('obd')?'OBD / testeri':'Perustarkastus',how:has('obd')?'Lue kaikki vikakoodit ennen nollausta. Tallenna freeze frame ja kuvaile tarkasti, milloin oire esiintyy.':'Kirjaa tarkasti milloin oire alkaa, lämpötila, nopeus, kuormitus ja varoitusvalot. Älä vaihda osia vielä.',expected:'Ensimmäisen vaiheen tarkoitus on kerätä tietoa, jolla seuraava fyysinen mittaus voidaan valita.',ok:'Aktivoi AI ja syötä saadut tiedot, niin palvelu valitsee seuraavan mittauksen.',bad:'Jos auto ylikuumenee, haisee voimakkaasti polttoaineelle, näyttää punaisen varoituksen tai turvallisuus vaarantuu, keskeytä ajo.',reason:'Järjestelmällinen vianhaku alkaa toistettavista havainnoista eikä komponenttiarvauksesta.'};}

function renderSources(sources=[]){if(!sourceStrip)return;if(!sources.length){sourceStrip.hidden=true;sourceStrip.innerHTML='';return;}sourceStrip.hidden=false;sourceStrip.innerHTML=sources.map(x=>`<span class="source-pill"><strong>${esc(x.name||'Data')}</strong> ${esc(x.provider||'')} · ${esc(x.detail||'')}</span>`).join('');}
function renderResult(r,source='ai',sources=[]){renderSources(sources);
 content.innerHTML=`<div class="result-card accent"><h4>Seuraava testi</h4><strong>${esc(r.test)}</strong><p>${esc(r.how)}</p></div><div class="result-card"><h4>Mittalaite</h4><strong>${esc(r.tool||'Ei määritetty')}</strong></div><div class="result-card"><h4>Mitä odotetaan</h4><p>${esc(r.expected||'Tarkka arvo riippuu ajoneuvosta ja on varmistettava teknisestä lähteestä.')}</p></div><div class="decision-grid"><div class="decision ok"><small>JOS TULOS ON NORMAALI</small><strong>${esc(r.ifNormal||r.ok||'Jatka seuraavaan mittaukseen.')}</strong></div><div class="decision bad"><small>JOS TULOS POIKKEAA</small><strong>${esc(r.ifAbnormal||r.bad||'Rajaa vikaa tämän löydöksen perusteella.')}</strong></div></div><div class="result-card"><h4>Miksi tämä mitataan</h4><p>${esc(r.reason||'Mittauksella rajataan mahdollisia juurisyitä ennen osien vaihtamista.')}</p></div>${r.caution?`<div class="result-card"><h4>Huomio</h4><p>${esc(r.caution)}</p></div>`:''}`;
 latestText=`AUTOSÄHKÖAPU AI\n\nSEURAAVA TESTI\n${r.test}\n\nMittalaite: ${r.tool||'-'}\nToimi näin: ${r.how}\nOdotettu: ${r.expected||'-'}\nJos normaali: ${r.ifNormal||r.ok||'-'}\nJos poikkeava: ${r.ifAbnormal||r.bad||'-'}\nMiksi: ${r.reason||'-'}`;
 panel.hidden=false;
 if(source==='free'){continueBox.hidden=true;paywallBox.hidden=false;}else{paywallBox.hidden=true;continueBox.hidden=false;}
 panel.scrollIntoView({behavior:'smooth',block:'start'});
}
function showLoading(){panel.hidden=false;paywallBox.hidden=true;continueBox.hidden=true;content.innerHTML='<div class="result-card"><div class="loading-line"><span class="spinner"></span><span>AI valitsee seuraavaa mittausta…</span></div></div>';}
function showError(msg){content.innerHTML=`<div class="result-card error-card"><h4>Yhteysvirhe</h4><p>${esc(msg)}</p></div>`;panel.hidden=false;}

form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);caseData={mode:fd.get('mode'),car:fd.get('car')?.trim(),vin:fd.get('vin')?.trim().toUpperCase(),year:fd.get('year')?.trim(),engine:fd.get('engine')?.trim(),dtc:fd.get('dtc')?.trim(),symptom:fd.get('symptom')?.trim(),done:fd.get('done')?.trim(),tools:tools(fd)};history=[];
 const typed=normalizeCode(accessCode.value);if(typed && (!activeAccess||activeAccess.code!==typed)) await activate();
 if(!activeAccess){
   if(freeUsed()){panel.hidden=false;continueBox.hidden=true;paywallBox.hidden=false;renderSources([]);content.innerHTML='<div class="result-card accent"><h4>Ilmainen kokeilu käytetty</h4><p>Olet käyttänyt yhden ilmaisen mittausohjeen tällä selaimella. Aktivoi käyttöpaketti jatkaaksesi AI-ohjattua diagnoosia.</p></div>';panel.scrollIntoView({behavior:'smooth',block:'start'});return;}
   const reply=localFreePlan(caseData);
   localStorage.setItem('asai_free_used','1');
   setAccessStatus('Ilmainen mittausohje käytetty. Maksullinen AI-jatko avautuu aktivointikoodilla.');
   renderResult(reply,'free',[]);
   return;
 }
 showLoading();try{const r=await api('/diagnose',{code:activeAccess.code,caseData,history,measurementResult:''});history=r.history||[];renderResult(r.reply,'ai',r.sources||[]);if(r.access){activeAccess={...activeAccess,...r.access};setAccessStatus(`${activeAccess.label||'Aktivoitu'}. ${r.access.remainingText||''}`,'ok');}}catch(err){showError(err.message);if(/koodi|käyttö|vanhen/i.test(err.message)) setAccessStatus(err.message,'bad');}
});

document.getElementById('continue-diagnosis').addEventListener('click',async()=>{if(!caseData||!activeAccess)return;const input=document.getElementById('measurement-result'),measurementResult=input.value.trim();if(!measurementResult){input.focus();return;}showLoading();try{const r=await api('/diagnose',{code:activeAccess.code,caseData,history,measurementResult});history=r.history||[];input.value='';renderResult(r.reply,'ai',r.sources||[]);if(r.access)setAccessStatus(`${activeAccess.label||'Aktivoitu'}. ${r.access.remainingText||''}`,'ok');}catch(err){showError(err.message);}});

document.getElementById('new-diagnosis').addEventListener('click',()=>{panel.hidden=true;continueBox.hidden=true;paywallBox.hidden=true;renderSources([]);history=[];caseData=null;document.getElementById('measurement-result').value='';window.location.hash='diagnoosi';document.getElementById('car').focus();});
document.getElementById('copy-result').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(latestText);document.getElementById('copy-status').textContent='Diagnoosipolku kopioitu.';}catch{document.getElementById('copy-status').textContent='Kopiointi ei onnistunut selaimessa.';}});
